config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def index
		@tasks = Task.all
	end

	def new
		@tasks = Task.new
	end

	def create
		@task = Task.create(task_params)
		redirect_to tasks_path
	end

	def edit
		@task = Task.find(params[:id])
	end

	def update
		@task = Task.find(params[:id])
		@task.update(task_params)
		redirect_to tasks_path
	end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		redirect_to tasks_path
	end

	private
		def task_params
			params.require(:task).permit(:title)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsToDoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
	<div id="idFooterArea">
		<%= link_to 'Home', tasks_path %>
		<%= link_to 'Add', new_task_path %>
	</div>
	<div>
		Copyright © <a href="https://ayato-shitomi.github.io/portfolio/">LabPixel Frameworks</a> All Rights Reserved.
	</div>
</footer>

app/views/shared/_header.html.erb
<header>
	<h1>The ToDo List</h1>
	<%= link_to 'Home', tasks_path %>
	<%= link_to 'Add', new_task_path %>
</header>

app/views/tasks/edit.html.erb
<%= render 'shared/header' %>

<h1>タスク編集</h1>
<%= form_for(@task) do |f| %>
	<div><%= f.label :title %></div>
	<div><%= f.text_field :title %></div>
	<div><%= f.submit %></div>
<% end %>
<%= link_to '戻る', tasks_path %>

<%= render 'shared/footer' %>

app/views/tasks/index.html.erb
<%= render 'shared/header' %>

<div id="idArea">
	<div id="classTitleButton">
		<div class="classTitle">ToDoリスト</div>
		<%= link_to 'タスク追加', new_task_path %>
	</div>

	<table>
		<thead>
			<tr>
				<th width=10%>Date</th>
				<th>ToDO</th>
				<th colspan="2" width="30%">Action</th>
			</tr>
		</thead>
		<tbody>
			<% @tasks.each do |task| %>
			<tr>
				<td style="word-break:break-word">2020/11/24</td>
				<td style="word-break:break-word"><%= task.title %></td>
				<td align="right" class="classClickToSomething"><%= link_to "📝", edit_task_path(task) %></td>
				<td class="classClickToSomething"><%= link_to "💪 / 🗑", task_path(task), method: :delete %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<%= render 'shared/footer' %>

app/views/tasks/new.html.erb
<%= render 'shared/header' %>


<div id="idArea">

	<div class="classTitle">タスク追加</div>

	<div id="idFormArea">
		<%= form_for @tasks do |f| %>
			<table>
				<tr id="idTaskInput">
					<td><div>タスクを入力</div></td>
					<td><div><%= f.text_field :title %></div></td>
				</tr>
				<tr id="idTaskInput">
					<td><div>タスクの期日を入力</div></td>
					<td><input></td>
				</tr>
				<tr id="idRadioBotton">
					<td><div>重要度</div></td>
					<td align="left">
						<div><input name="priority" type="radio" value="">⚠️</div>
						<div><input name="priority" type="radio" value="" checked>✅</div>
						<div><input name="priority" type="radio" value="">💩</div>
					</td>
				</tr>
			</table>
			<div><%= f.submit "タスクを保存する"%></div>
		<% end %>
	</div>

	<div id="classTitleButton">
		<%= link_to '保存せずに戻る', tasks_path %>
	</div>
</div>

<%= render 'shared/footer' %>